[project]
ref = "rzzqfxploworizteqgjv"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54323

[studio]
port = 54323

[ingest]
port = 54324

[storage]
file_size_limit = "5MiB"

[auth]
site_url = "http://localhost:5174"
additional_redirect_urls = ["https://localhost:5174"]
jwt_expiry = 3600

[analytics]
port = 54327
